name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: gem install awesome_bot
    - run: awesome_bot README.md -a 429 --allow-redirect --allow-dupe
